### ISSUE TITLE
Load the combined CSV to memory and perform a simple EDA - @zackt113

### ISSUE THREAD

**Issue by MacyChan** [UBC-MDS/web_and_cloud_group_1#2]

**Comment by MacyChan** [comment]
https://github.com/UBC-MDS/web_and_cloud_group_1/pull/5#pullrequestreview-925441917

comment and fixed in PR

**Comment by MacyChan** [comment]
@zackt113 
For the comment description, I think we should avoid using exact number for the time since we have different results every run. For example, 
```
By loading data in chunks with a chunk size of 10 million, we can reduce the loading time to 1min and 3s!
```

```
As our main interest is the rainfall, so in order to speed up the process, we only load the needed columns. By reducing the number of columns, we are able to reduce the time to 34.5 sec
```

If you want to use print(f' xxx {var} xxx'), you can try using %%timeit
https://stackoverflow.com/questions/52738709/how-to-store-time-values-in-a-variable-in-jupyter

**Comment by zackt113** [comment]
Thank you, Macy, I will update it!

**Comment by zackt113** [comment]
As the comment is so long, so I just delete the specific time and describe the result in words. Using %%timeit in a cell may be too messy given that we already have a lot of codes.
