### ISSUE TITLE
Perform a simple EDA in R - @stevenleung2018

### ISSUE THREAD

**Issue by stevenleung2018** [UBC-MDS/web_and_cloud_group_1#4]

**Comment by stevenleung2018** [comment]
There is an issue with R loading a parquet file.  I have posted on slack.  https://ubc-mds.slack.com/archives/C24J4AQT1/p1648543553535309 

Please note that I tried to do the same thing from R console and it also crashes.  I will continue to troubleshoot.

**Comment by stevenleung2018** [comment]
FYI, I got R to work reading the file in feather format.  I already can convert CSV into feather.  So it is good news that we at least have one thing working.  I will go to Gittu's OH today to find out why Python/R can't read the parquet file with `arrow`.

**Comment by stevenleung2018** [comment]
@jo4356 When you have your performance numbers, please don't do it with PR.  You can write a comment there with this issue and I can enter your metrics into the tables manually.

**Comment by jo4356** [comment]
@stevenleung2018 Done:
- Change data types:  3min 48s
- Load what is needed: 1min 26s
- Load data in chunks: 2min 16s

**Comment by MacyChan** [comment]
@stevenleung2018 
1. Some desciption related to feather, I think we are fine with it now so it is not needed?
```
We tried to save the dataframe to feather file and read it into R, but there is an unknown issue with arrow that the R kernel dies.
```

2. I think we can just say we tried another method, and it takes much longer (which is a very good support on why we are using feather!)
```
The following is the backup code (Pandas Exchange, commented out) just in case arrow's reading of feather file does not execute correctly. The following code will take about 14 minutes to run.
```

3. One of the requirements for milestone 1 is `Discuss why you chose this approach over others.`. Should we add a small subtitle and write up something? (guess we have done enough already, we tried two methods, one is slow. and the nice thing about using feather is that file can be passed around and do not need to reload it every time .)

**Comment by stevenleung2018** [comment]
Since I can't run `arrow` on my computer, I'm rewriting the text below.  Can you copy and paste it to your notebook and commit the changes?  Since we are not changing the code cells, you don't need to rerun the notebook.

> @stevenleung2018
> 
> 1. Some desciption related to feather, I think we are fine with it now so it is not needed?
> 
> ```
> We tried to save the dataframe to feather file and read it into R, but there is an unknown issue with arrow that the R kernel dies.
> ```

I thought I changed this already.  Perhaps it was left out even though the code has been rearranged.  Sorry.  Let's write the following:

#### Comparison of methods of moving dataframe from Python to R:
- We have tried 2 methods, namely the feather file format and Pandas Exchange, and have decided to use the feather file format (saving the Pandas dataframe to `feather` file, and reading it in R with `arrow` package) because the speed is a lot faster.  The Pandas Exchange (aka IPython or R magic) is very slow (taking about 14 minutes for the dataframe concerned), probably due to the need to convert a 1GB Pandas dataframe into a data format R can accept.  The other advantage of saving it to `feather` file to disk is that we can easily resume from the saved snapshot of the data if the analysis was interrupted.

>  2. I think we can just say we tried another method, and it takes much longer (which is a very good support on why we are using feather!)
> 
> ```
> The following is the backup code (Pandas Exchange, commented out) just in case arrow's reading of feather file does not execute correctly. The following code will take about 14 minutes to run.
> ```
> 
>  3. One of the requirements for milestone 1 is `Discuss why you chose this approach over others.`. Should we add a small subtitle and write up something? (guess we have done enough already, we tried two methods, one is slow. and the nice thing about using feather is that file can be passed around and do not need to reload it every time .)

I think the paragraph I wrote above should be sufficient.

**Comment by MacyChan** [comment]
Sorry @stevenleung2018 I missed the above instruction (about copy and paste).
The notebook needed to rerun because the numbers of ran cells were not in order.
However, like mentioned in Slack, the histogram was too large and I end up couldn't run the last cell.
Would you mind to pull the notebook, edit back the words and edit the EDA?
I can help run the whole thing again once it is done! Thank you =]

**Comment by MacyChan** [comment]
* We do not need to do crazy EDA due to the volume of the data?

**Comment by stevenleung2018** [comment]
@MacyChan I'm going to type some suggested changes (mostly text) here and then please make those changes to the notebook.

**Comment by stevenleung2018** [comment]
@MacyChan 
Original line:
Load just the columns we want (df_2)
Should be changed to:
Load just the columns we want (df_1)

**Comment by stevenleung2018** [comment]
@MacyChan 
Original line:
df_2 is close to 1GB. 
Should be changed to:
df_1 is close to 1.6GB.

**Comment by stevenleung2018** [comment]
@MacyChan 
Original code cell (#39):
```
# %%time
# %%R -i df_2
# head(df_2) 
```
Change to:
```
# %%time
# %%R -i df_1
# head(df_1) 
```

**Comment by stevenleung2018** [comment]
@MacyChan 
Original code cell #40:
```
# %%R
# object.size(df_2)
```
Change to:
```
# %%R
# object.size(df_1)
```

**Comment by stevenleung2018** [comment]
@MacyChan 
Original line (right above code cell 39):
The following code will take about 14 minutes to run.
Change to:
The following code will take more than 22 minutes to run.

**Comment by MacyChan** [comment]
@stevenleung2018 Is there any reason you can not make a commit on the notebook of your part? I maybe able to help for the technical issue. ;) Don’t  worry about asking! We can figure it out together. Thanks!

**Comment by stevenleung2018** [comment]
@MacyChan 
Original text:
It takes a long time for Pandas Exchange to pass the df_2 to R. The following is the output from running the above cell one time:
Change to:
It takes a long time for Pandas Exchange to pass the `df_2` to R. The following is the output from running the above cell if `df_2` is used:

**Comment by MacyChan** [comment]
Btw, please check the latest notebook, I think I have edited and reran the coding part. Just the text parts are left 👀 Lemme know if you have any questions

**Comment by stevenleung2018** [comment]
@MacyChan Per discussed, I will make the changes I mentioned above instead of by you.  Will be done by tonight (probably earlier).

**Comment by stevenleung2018** [comment]
Just for the record, I tried to load R with `df_1` through R magic.  It took 2h 19min 26s.
The code:
```r
%%time
%%R -i df_1
head(df_1) 
```
The output:
```r
   lat_min  lat_max lon_min lon_max rain (mm/day)           model
1 -35.4375 -33.5625   141.5   143.5             0 MPI-ESM-1-2-HAM
2 -35.4375 -33.5625   141.5   143.5             0 MPI-ESM-1-2-HAM
3 -35.4375 -33.5625   141.5   143.5             0 MPI-ESM-1-2-HAM
4 -35.4375 -33.5625   141.5   143.5             0 MPI-ESM-1-2-HAM
5 -35.4375 -33.5625   141.5   143.5             0 MPI-ESM-1-2-HAM
6 -35.4375 -33.5625   141.5   143.5             0 MPI-ESM-1-2-HAM
CPU times: user 1h 1min 25s, sys: 47min 1s, total: 1h 48min 26s
Wall time: 2h 19min 26s
```

**Comment by MacyChan** [comment]
Feel like you should add this too the notebook since you and your computer worked so hard lol

**Comment by stevenleung2018** [comment]
@MacyChan I just updated the notebook as you suggested.  :-)
